import axios from 'axios';

export const REQUEST_MOVIE_DATA = 'REQUEST_MOVIE_DATA';
export const REQUEST_MOVIE_DATA_ERROR = 'REQUEST_MOVIE_DATA_ERROR';
export const REQUEST_MOVIE_DATA_SUCCESS = 'REQUEST_MOVIE_DATA_SUCCESS';